### ISSUE TITLE
Request to evaluate the new O1 models by OpenAI (O1-preview and O1-mini)

### ISSUE THREAD

**Issue by Belzedar94** [marzenakrp/nocha#1] opened 2024-09-14 07:51 UTC
Request in title. Thanks!! :)

**Comment by marzenakrp** [comment] 2024-09-14 13:49
We are trying... The issue is that we are getting "server error" with long input for many (but not all) books. 

We were able to run short stories so far (these are much easier and the length is about 5k-20k for a story) and the results are:
o1-preview-2024-09-12-story: 68.1 (47/69)
o1-mini-2024-09-12-story: 56.5 (39/69)

For comparison, some other models we run on short stories (and report in the paper as mini-experiments):
gpt4o-story: 65.2 (45/69)
claude3opus-story: 63.8 (44/69)
qwen2-72B-instruct-story: 60.9 (42/69)
mixtral-8x22B-story: 56.5 (39/69)
gemini1.5pro-story: 51.5 (35/68) (one rejected due to claim content being evaluated as "unsafe")
gpt-4-turbo-story: 50.7 (35/69)

NOTE: stories are NOT part of NoCha data we evaluate on for the benchmark, but rather our sanity check on how well models handle much shorter context for similar task. The claims are often easier and the input is much shorter.

We will update the benchmark with o1-preview/mini as soon as we can process at least some more books :) (the fact that there is no way of telling how much "reasoning_tokens" the model produce doesn't really help -  we've seen it getting stuck and going over 4k at times...)

**Comment by marzenakrp** [comment] 2024-09-14 13:50
Will close this for now and work on getting this data if API permits.

**Closed as completed by marzenakrp** 2024-09-14 13:50 UTC
